In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Warehouse_and_Retail_Sales.csv')

In [3]:
df

,YEAR,MONTH,SUPPLIER,ITEM CODE,ITEM DESCRIPTION,ITEM TYPE,RETAIL SALES,RETAIL TRANSFERS,WAREHOUSE SALES
0,2020,1,REPUBLIC NATIONAL DISTRIBUTING CO,100009,BOOTLEG RED - 750ML,WINE,0.00,0.0,2.00
1,2020,1,PWSWN INC,100024,MOMENT DE PLAISIR - 750ML,WINE,0.00,1.0,4.00
2,2020,1,RELIABLE CHURCHILL LLLP,1001,S SMITH ORGANIC PEAR CIDER - 18.7OZ,BEER,0.00,0.0,1.00
3,2020,1,LANTERNA DISTRIBUTORS INC,100145,SCHLINK HAUS KABINETT - 750ML,WINE,0.00,0.0,1.00
4,2020,1,DIONYSOS IMPORTS INC,100293,SANTORINI GAVALA WHITE - 750ML,WINE,0.82,0.0,0.00
...,...,...,...,...,...,...,...,...,...
307640,2020,9,DOPS INC,97896,ST PETERS ORGANIC ENG ALE NR 12/CS - 16.9OZ,BEER,0.00,0.0,1.00
307641,2020,9,ANHEUSER BUSCH INC,97918,STELLA ARTOIS 2/12 NR - 11.2OZ,BEER,372.45,315.0,3586.88
307642,2020,9,HEINEKEN USA,97942,TECATE 4/6 LNNR - 12OZ,BEER,7.79,0.0,4.00
307643,2020,9,RELIABLE CHURCHILL LLLP,97950,S SMITH WINTER WELCOME NR 12/CS - 18.7OZ,BEER,0.00,0.0,2.00
307644,2020,9,RELIABLE CHURCHILL LLLP,97969,S SMITH WINTER WELCOME 4/6NR - 12OZ,BEER,0.00,0.0,1.00

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307645 entries, 0 to 307644
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   YEAR              307645 non-null  int64
 1   MONTH             307645 non-null  int64
 2   SUPPLIER          307478 non-null  object
 3   ITEM CODE         307645 non-null  object
 4   ITEM DESCRIPTION  307645 non-null  object
 5   ITEM TYPE         307644 non-null  object
 6   RETAIL SALES      307642 non-null  float64
 7   RETAIL TRANSFERS  307645 non-null  float64
 8   WAREHOUSE SALES   307645 non-null  float64
dtypes: float64(3), int64(2), object(4)
memory usage: 21.1+ MB

In [5]:
df.describe()

,YEAR,MONTH,RETAIL SALES,RETAIL TRANSFERS,WAREHOUSE SALES
count,307645.000000,307645.000000,307642.000000,307645.000000,307645.000000
mean,2018.438525,6.423862,7.024071,6.936465,25.294597
std,1.083061,3.461812,30.986238,30.237195,249.916798
min,2017.000000,1.000000,-6.490000,-38.490000,-7800.000000
25%,2017.000000,3.000000,0.000000,0.000000,0.000000
50%,2019.000000,7.000000,0.320000,0.000000,1.000000
75%,2019.000000,9.000000,3.267500,3.000000,5.000000
max,2020.000000,12.000000,2739.000000,1990.830000,18317.000000

In [ ]:
Dealing with missing values:

In [ ]:
Filling missing values in SUPPLIER column with N/A in place of null values.

In [6]:
df['SUPPLIER'].fillna('N/A',inplace=True)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307645 entries, 0 to 307644
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   YEAR              307645 non-null  int64
 1   MONTH             307645 non-null  int64
 2   SUPPLIER          307645 non-null  object
 3   ITEM CODE         307645 non-null  object
 4   ITEM DESCRIPTION  307645 non-null  object
 5   ITEM TYPE         307644 non-null  object
 6   RETAIL SALES      307642 non-null  float64
 7   RETAIL TRANSFERS  307645 non-null  float64
 8   WAREHOUSE SALES   307645 non-null  float64
dtypes: float64(3), int64(2), object(4)
memory usage: 21.1+ MB

In [ ]:
Filling missing values in ITEM TYPE column with N/A in place of null values.

In [8]:
df['ITEM TYPE'].fillna('N/A',inplace=True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307645 entries, 0 to 307644
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   YEAR              307645 non-null  int64
 1   MONTH             307645 non-null  int64
 2   SUPPLIER          307645 non-null  object
 3   ITEM CODE         307645 non-null  object
 4   ITEM DESCRIPTION  307645 non-null  object
 5   ITEM TYPE         307645 non-null  object
 6   RETAIL SALES      307642 non-null  float64
 7   RETAIL TRANSFERS  307645 non-null  float64
 8   WAREHOUSE SALES   307645 non-null  float64
dtypes: float64(3), int64(2), object(4)
memory usage: 21.1+ MB

In [ ]:
Filling missing values in RETAIL SALES  column with mean in place of null values.

In [10]:
df['RETAIL SALES'].fillna(df['RETAIL SALES'].mean(),inplace=True)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307645 entries, 0 to 307644
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   YEAR              307645 non-null  int64
 1   MONTH             307645 non-null  int64
 2   SUPPLIER          307645 non-null  object
 3   ITEM CODE         307645 non-null  object
 4   ITEM DESCRIPTION  307645 non-null  object
 5   ITEM TYPE         307645 non-null  object
 6   RETAIL SALES      307645 non-null  float64
 7   RETAIL TRANSFERS  307645 non-null  float64
 8   WAREHOUSE SALES   307645 non-null  float64
dtypes: float64(3), int64(2), object(4)
memory usage: 21.1+ MB

In [12]:
df.nunique()

YEAR                    4
MONTH                  12
SUPPLIER              397
ITEM CODE           34056
ITEM DESCRIPTION    34822
ITEM TYPE               9
RETAIL SALES        10675
RETAIL TRANSFERS     2504
WAREHOUSE SALES      4895
dtype: int64

In [ ]:
Transforming month from numbers to text.

In [13]:
month_map = {1:'January',2:'February',3:'March',4:'April',5:'May',6:'June',7:'July',8:'August',
         9:'September',10:'October',11:'November',12:'December'}
df['MONTH'] = df['MONTH'].map(month_map)

In [14]:
df

,YEAR,MONTH,SUPPLIER,ITEM CODE,ITEM DESCRIPTION,ITEM TYPE,RETAIL SALES,RETAIL TRANSFERS,WAREHOUSE SALES
0,2020,January,REPUBLIC NATIONAL DISTRIBUTING CO,100009,BOOTLEG RED - 750ML,WINE,0.00,0.0,2.00
1,2020,January,PWSWN INC,100024,MOMENT DE PLAISIR - 750ML,WINE,0.00,1.0,4.00
2,2020,January,RELIABLE CHURCHILL LLLP,1001,S SMITH ORGANIC PEAR CIDER - 18.7OZ,BEER,0.00,0.0,1.00
3,2020,January,LANTERNA DISTRIBUTORS INC,100145,SCHLINK HAUS KABINETT - 750ML,WINE,0.00,0.0,1.00
4,2020,January,DIONYSOS IMPORTS INC,100293,SANTORINI GAVALA WHITE - 750ML,WINE,0.82,0.0,0.00
...,...,...,...,...,...,...,...,...,...
307640,2020,September,DOPS INC,97896,ST PETERS ORGANIC ENG ALE NR 12/CS - 16.9OZ,BEER,0.00,0.0,1.00
307641,2020,September,ANHEUSER BUSCH INC,97918,STELLA ARTOIS 2/12 NR - 11.2OZ,BEER,372.45,315.0,3586.88
307642,2020,September,HEINEKEN USA,97942,TECATE 4/6 LNNR - 12OZ,BEER,7.79,0.0,4.00
307643,2020,September,RELIABLE CHURCHILL LLLP,97950,S SMITH WINTER WELCOME NR 12/CS - 18.7OZ,BEER,0.00,0.0,2.00
307644,2020,September,RELIABLE CHURCHILL LLLP,97969,S SMITH WINTER WELCOME 4/6NR - 12OZ,BEER,0.00,0.0,1.00

In [ ]:
Changing case of SUPPLIER,ITEM DESCRIPTION column to Proper-case

In [15]:
df['SUPPLIER'] = df['SUPPLIER'].str.title()

In [16]:
df

,YEAR,MONTH,SUPPLIER,ITEM CODE,ITEM DESCRIPTION,ITEM TYPE,RETAIL SALES,RETAIL TRANSFERS,WAREHOUSE SALES
0,2020,January,Republic National Distributing Co,100009,BOOTLEG RED - 750ML,WINE,0.00,0.0,2.00
1,2020,January,Pwswn Inc,100024,MOMENT DE PLAISIR - 750ML,WINE,0.00,1.0,4.00
2,2020,January,Reliable Churchill Lllp,1001,S SMITH ORGANIC PEAR CIDER - 18.7OZ,BEER,0.00,0.0,1.00
3,2020,January,Lanterna Distributors Inc,100145,SCHLINK HAUS KABINETT - 750ML,WINE,0.00,0.0,1.00
4,2020,January,Dionysos Imports Inc,100293,SANTORINI GAVALA WHITE - 750ML,WINE,0.82,0.0,0.00
...,...,...,...,...,...,...,...,...,...
307640,2020,September,Dops Inc,97896,ST PETERS ORGANIC ENG ALE NR 12/CS - 16.9OZ,BEER,0.00,0.0,1.00
307641,2020,September,Anheuser Busch Inc,97918,STELLA ARTOIS 2/12 NR - 11.2OZ,BEER,372.45,315.0,3586.88
307642,2020,September,Heineken Usa,97942,TECATE 4/6 LNNR - 12OZ,BEER,7.79,0.0,4.00
307643,2020,September,Reliable Churchill Lllp,97950,S SMITH WINTER WELCOME NR 12/CS - 18.7OZ,BEER,0.00,0.0,2.00
307644,2020,September,Reliable Churchill Lllp,97969,S SMITH WINTER WELCOME 4/6NR - 12OZ,BEER,0.00,0.0,1.00

In [17]:
df['ITEM DESCRIPTION'] = df['ITEM DESCRIPTION'].str.title()

In [18]:
df

,YEAR,MONTH,SUPPLIER,ITEM CODE,ITEM DESCRIPTION,ITEM TYPE,RETAIL SALES,RETAIL TRANSFERS,WAREHOUSE SALES
0,2020,January,Republic National Distributing Co,100009,Bootleg Red - 750Ml,WINE,0.00,0.0,2.00
1,2020,January,Pwswn Inc,100024,Moment De Plaisir - 750Ml,WINE,0.00,1.0,4.00
2,2020,January,Reliable Churchill Lllp,1001,S Smith Organic Pear Cider - 18.7Oz,BEER,0.00,0.0,1.00
3,2020,January,Lanterna Distributors Inc,100145,Schlink Haus Kabinett - 750Ml,WINE,0.00,0.0,1.00
4,2020,January,Dionysos Imports Inc,100293,Santorini Gavala White - 750Ml,WINE,0.82,0.0,0.00
...,...,...,...,...,...,...,...,...,...
307640,2020,September,Dops Inc,97896,St Peters Organic Eng Ale Nr 12/Cs - 16.9Oz,BEER,0.00,0.0,1.00
307641,2020,September,Anheuser Busch Inc,97918,Stella Artois 2/12 Nr - 11.2Oz,BEER,372.45,315.0,3586.88
307642,2020,September,Heineken Usa,97942,Tecate 4/6 Lnnr - 12Oz,BEER,7.79,0.0,4.00
307643,2020,September,Reliable Churchill Lllp,97950,S Smith Winter Welcome Nr 12/Cs - 18.7Oz,BEER,0.00,0.0,2.00
307644,2020,September,Reliable Churchill Lllp,97969,S Smith Winter Welcome 4/6Nr - 12Oz,BEER,0.00,0.0,1.00

In [19]:
df['ITEM TYPE'] = df['ITEM TYPE'].str.title()

In [20]:
df

,YEAR,MONTH,SUPPLIER,ITEM CODE,ITEM DESCRIPTION,ITEM TYPE,RETAIL SALES,RETAIL TRANSFERS,WAREHOUSE SALES
0,2020,January,Republic National Distributing Co,100009,Bootleg Red - 750Ml,Wine,0.00,0.0,2.00
1,2020,January,Pwswn Inc,100024,Moment De Plaisir - 750Ml,Wine,0.00,1.0,4.00
2,2020,January,Reliable Churchill Lllp,1001,S Smith Organic Pear Cider - 18.7Oz,Beer,0.00,0.0,1.00
3,2020,January,Lanterna Distributors Inc,100145,Schlink Haus Kabinett - 750Ml,Wine,0.00,0.0,1.00
4,2020,January,Dionysos Imports Inc,100293,Santorini Gavala White - 750Ml,Wine,0.82,0.0,0.00
...,...,...,...,...,...,...,...,...,...
307640,2020,September,Dops Inc,97896,St Peters Organic Eng Ale Nr 12/Cs - 16.9Oz,Beer,0.00,0.0,1.00
307641,2020,September,Anheuser Busch Inc,97918,Stella Artois 2/12 Nr - 11.2Oz,Beer,372.45,315.0,3586.88
307642,2020,September,Heineken Usa,97942,Tecate 4/6 Lnnr - 12Oz,Beer,7.79,0.0,4.00
307643,2020,September,Reliable Churchill Lllp,97950,S Smith Winter Welcome Nr 12/Cs - 18.7Oz,Beer,0.00,0.0,2.00
307644,2020,September,Reliable Churchill Lllp,97969,S Smith Winter Welcome 4/6Nr - 12Oz,Beer,0.00,0.0,1.00

In [ ]:
Deleting unwanted columns

In [ ]:
In some cases we dont need  to use some columns, in such scenarios we can delete unwanted columns

In [21]:
df1 = df.drop(['RETAIL TRANSFERS'],axis=1)

In [22]:
df1

,YEAR,MONTH,SUPPLIER,ITEM CODE,ITEM DESCRIPTION,ITEM TYPE,RETAIL SALES,WAREHOUSE SALES
0,2020,January,Republic National Distributing Co,100009,Bootleg Red - 750Ml,Wine,0.00,2.00
1,2020,January,Pwswn Inc,100024,Moment De Plaisir - 750Ml,Wine,0.00,4.00
2,2020,January,Reliable Churchill Lllp,1001,S Smith Organic Pear Cider - 18.7Oz,Beer,0.00,1.00
3,2020,January,Lanterna Distributors Inc,100145,Schlink Haus Kabinett - 750Ml,Wine,0.00,1.00
4,2020,January,Dionysos Imports Inc,100293,Santorini Gavala White - 750Ml,Wine,0.82,0.00
...,...,...,...,...,...,...,...,...
307640,2020,September,Dops Inc,97896,St Peters Organic Eng Ale Nr 12/Cs - 16.9Oz,Beer,0.00,1.00
307641,2020,September,Anheuser Busch Inc,97918,Stella Artois 2/12 Nr - 11.2Oz,Beer,372.45,3586.88
307642,2020,September,Heineken Usa,97942,Tecate 4/6 Lnnr - 12Oz,Beer,7.79,4.00
307643,2020,September,Reliable Churchill Lllp,97950,S Smith Winter Welcome Nr 12/Cs - 18.7Oz,Beer,0.00,2.00
307644,2020,September,Reliable Churchill Lllp,97969,S Smith Winter Welcome 4/6Nr - 12Oz,Beer,0.00,1.00

In [ ]:
Deleting unwanted rows

In [ ]:
Categorical columns may contain uncertain values such as 'N/A','None',

In [ ]:
Deleting rows from the column SUPPLIER where the value is 'N/A'

In [23]:
for x in df1.index:
    if(df1.loc[x,'SUPPLIER']=='N/A'):
        df1.drop(x,inplace=True)

In [24]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 307478 entries, 0 to 307644
Data columns (total 8 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   YEAR              307478 non-null  int64
 1   MONTH             307478 non-null  object
 2   SUPPLIER          307478 non-null  object
 3   ITEM CODE         307478 non-null  object
 4   ITEM DESCRIPTION  307478 non-null  object
 5   ITEM TYPE         307478 non-null  object
 6   RETAIL SALES      307478 non-null  float64
 7   WAREHOUSE SALES   307478 non-null  float64
dtypes: float64(2), int64(1), object(5)
memory usage: 29.2+ MB

In [ ]:
Deleting rows from column ITEM TYPE where value is ITEM TYPE 'N/A'

In [25]:
for x in df1.index:
    if(df1.loc[x,'ITEM TYPE']=='N/A'):
        df1.drop(x,inplace=True)

In [26]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 307477 entries, 0 to 307644
Data columns (total 8 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   YEAR              307477 non-null  int64
 1   MONTH             307477 non-null  object
 2   SUPPLIER          307477 non-null  object
 3   ITEM CODE         307477 non-null  object
 4   ITEM DESCRIPTION  307477 non-null  object
 5   ITEM TYPE         307477 non-null  object
 6   RETAIL SALES      307477 non-null  float64
 7   WAREHOUSE SALES   307477 non-null  float64
dtypes: float64(2), int64(1), object(5)
memory usage: 29.2+ MB

In [27]:
df1

,YEAR,MONTH,SUPPLIER,ITEM CODE,ITEM DESCRIPTION,ITEM TYPE,RETAIL SALES,WAREHOUSE SALES
0,2020,January,Republic National Distributing Co,100009,Bootleg Red - 750Ml,Wine,0.00,2.00
1,2020,January,Pwswn Inc,100024,Moment De Plaisir - 750Ml,Wine,0.00,4.00
2,2020,January,Reliable Churchill Lllp,1001,S Smith Organic Pear Cider - 18.7Oz,Beer,0.00,1.00
3,2020,January,Lanterna Distributors Inc,100145,Schlink Haus Kabinett - 750Ml,Wine,0.00,1.00
4,2020,January,Dionysos Imports Inc,100293,Santorini Gavala White - 750Ml,Wine,0.82,0.00
...,...,...,...,...,...,...,...,...
307640,2020,September,Dops Inc,97896,St Peters Organic Eng Ale Nr 12/Cs - 16.9Oz,Beer,0.00,1.00
307641,2020,September,Anheuser Busch Inc,97918,Stella Artois 2/12 Nr - 11.2Oz,Beer,372.45,3586.88
307642,2020,September,Heineken Usa,97942,Tecate 4/6 Lnnr - 12Oz,Beer,7.79,4.00
307643,2020,September,Reliable Churchill Lllp,97950,S Smith Winter Welcome Nr 12/Cs - 18.7Oz,Beer,0.00,2.00
307644,2020,September,Reliable Churchill Lllp,97969,S Smith Winter Welcome 4/6Nr - 12Oz,Beer,0.00,1.00